name: Create Release Draft

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:

jobs:
  windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Ignore lines containing 'version = "x.x.x"' and hash the rest of Cargo.lock
      - name: Generate custom cache key
        id: cargo-hash
        run: |
          grep -v '^version = ' src-tauri/Cargo.lock | shasum -a 256 | awk '{ print $1 }' > cargo_hash.txt
          echo "CARGO_CACHE_KEY=$(cat cargo_hash.txt)" >> $GITHUB_ENV
          echo "::set-output name=CARGO_CACHE_KEY::$(cat cargo_hash.txt)"

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: C:/Users/runneradmin/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ steps.cargo-hash.outputs.CARGO_CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo git index
        uses: actions/cache@v4
        with:
          path: C:/Users/runneradmin/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ steps.cargo-hash.outputs.CARGO_CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Tauri CLI if not cached
        run: cargo install tauri-cli --version "1"
        if: steps.tauri-cli-cache.outputs.cache-hit != 'true'

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Node Module
        run: npm i pnpm -g && pnpm i
        env:
          PATH: C:/Users/runneradmin/AppData/Roaming/npm:${{ env.PATH }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "22.2"

      - name: Build
        run: cargo tauri build
        working-directory: ./src-tauri

      - name: Create output directory
        run: mkdir -Force output
        shell: pwsh

      - name: Copy files to output
        run: cp src-tauri/target/release/bundle/nsis/*.exe output/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: ${{ github.workspace }}/output/*.exe
